export const tasks = [
  {
    id: 1,
    title: 'Daily meeting with team',
    start: '10:00 AM',
    end: '10:30 AM',
    duration: '30 min',
  },
  {
    id: 2,
    title: 'Design standup',
    start: '10:30 AM',
    end: '11:00 AM',
    duration: '30 min',
  },
  {
    id: 3,
    title: 'Weekly sprint planning',
    start: '11:00 AM',
    end: '12:00 PM',
    duration: '1 hr',
  },
  {
    id: 4,
    title: 'Lunch break',
    start: '12:00 PM',
    end: '1:00 PM',
    duration: '1 hr',
  },
  {
    id: 5,
    title: 'Client meeting',
    start: '1:00 PM',
    end: '2:00 PM',
    duration: '1 hr',
  },
  {
    id: 6,
    title: 'Project brainstorming',
    start: '2:00 PM',
    end: '3:00 PM',
    duration: '1 hr',
  },
  {
    id: 7,
    title: 'Code review',
    start: '3:00 PM',
    end: '4:00 PM',
    duration: '1 hr',
  },
  {
    id: 8,
    title: 'Documentation update',
    start: '4:00 PM',
    end: '5:00 PM',
    duration: '1 hr',
  },
  {
    id: 9,
    title: 'Wrap up and plan for tomorrow',
    start: '5:00 PM',
    end: '5:30 PM',
    duration: '30 min',
  },
];
